UPDATE `sections` SET `section_icon` = 'fa fa-refresh' WHERE `sections`.`id` = 24;


INSERT INTO `cities` (`city`, `state_id`)
VALUES ('Kanpur', '75'),
('Agra', 75),
('Allahabad', 75),
('Aligarh', 75),
('Ambedkar Nagar', 75),
('Auraiya', 75),
('Azamgarh', 75),
('Barabanki', 75),
('Badaun', 75),
('Bagpat', 75),
('Bahraich', 75),
( 'Bijnor', 75),
( 'Ballia', 75),
( 'Banda', 75),
( 'Balrampur', 75),
( 'Bareilly', 75),
( 'Basti', 75),
( 'Bulandshahr', 75),
( 'Chandauli', 75),
( 'Chitrakoot', 75),
( 'Deoria', 75),
( 'Etah', 75),
( 'Kanshiram Nagar', 75),
( 'Etawah', 75),
( 'Firozabad', 75),
( 'Farrukhabad', 75),
( 'Fatehpur', 75),
( 'Faizabad', 75),
( 'Gautam Buddha Nagar', 75),
( 'Gonda', 75),
( 'Ghazipur', 75),
( 'Gorkakhpur', 75),
( 'Ghaziabad', 75),
( 'Hamirpur', 75),
( 'Hardoi', 75),
( 'Mahamaya Nagar', 75),
( 'Jhansi', 75),
( 'Jalaun', 75),
( 'Jyotiba Phule Nagar', 75),
( 'Jaunpur District', 75), 
( 'Kannauj', 75), 
( 'Kaushambi', 75),
( 'Kushinagar', 75),
( 'Lalitpur', 75),
( 'Lakhimpur Kheri', 75),
( 'Lucknow', 75),
( 'Mau', 75),
( 'Meerut', 75),
( 'Maharajganj', 75),
( 'Mahoba', 75),
( 'Mirzapur', 75),
( 'Moradabad', 75),
( 'Mainpuri', 75),
( 'Mathura', 75),
( 'Muzaffarnagar', 75),
( 'Pilibhit', 75),
( 'Pratapgarh', 75),
( 'Rampur', 75),
( 'Rae Bareli', 75),
( 'Saharanpur', 75),
( 'Sitapur', 75),
( 'Shahjahanpur', 75),
( 'Sant Kabir Nagar', 75),
( 'Siddharthnagar', 75),
( 'Sonbhadra', 75),
( 'Sant Ravidas Nagar', 75),
( 'Sultanpur', 75),
( 'Shravasti', 75),
( 'Unnao', 75),
( 'Varanasi', 75);

UPDATE `loading_receipts` SET `consignee_country_id` = '27' WHERE `consignor_country_id` = 0 and `consignee_country_id` = 0;
UPDATE `loading_receipts` SET `consignor_country_id` = '27' WHERE `consignor_country_id` = 0 and `consignee_country_id` =0;
